
## Question 3

```{r message=F, warning=F}
library(dplyr)
library(ggplot2)
library(stringr)
library(ggrepel)
library(vegan)
source("http://bit.ly/theme_pub")
```

```{r}
data = read.table("rawGeneExpression.txt", header=T, sep = "\t")

# remove unwanted columns & rename
data = data %>% 
  select(1:5) %>%
  rename(Bacteria = X) %>%
  mutate(across(2:5, as.numeric))

data$Bacteria = str_extract(data$Bacteria, "^[^;]+") # removing extra stuff from bacteria name
```

```{r warning=F}
PCA_data = decostand(data[2:5], method = "hellinger") # scale data

PCA = princomp(PCA_data, cor=T) # run PCA

PCA_data$PC1 = PCA$scores[,1] # getting PC axes for plot
PCA_data$PC2 = PCA$scores[,2]
PCA_data$PC3 = PCA$scores[,3]
PCA_data$Bacteria = data$Bacteria # add names back for colour coding

x = ggplot(data=PCA_data, aes(x=PC1, y=PC2, colour=PC3)) + geom_point() + theme_pub() + scale_color_gradient(low = "lightblue", high = "red")
```

```{r}
summary(PCA)
str(PCA)
```

```{r}
# get labels
labels = function(x) {
  words = unlist(strsplit(x, " "))
  abbr = paste0(substr(words, 1, 1), collapse = ".")
  return(abbr)
}

# add labels
PCA_data = PCA_data %>%
    mutate(label = sapply(Bacteria, labels))

# plot with labels
options(ggrepel.max.overlaps = Inf) # need this for all labels

x + theme_pub() + geom_text_repel(data = PCA_data, aes(label = ifelse(Bacteria == "Rickettsia buchneri", "", label)), size = 3, alpha = 0.5,)

# the unlabeled points are Rickettsia buchneri
```

```{r warning=F}
# set up data for correlation calculations
grouped_data = PCA_data %>%
  group_by(Bacteria) %>%
  summarise(across(starts_with("X"), mean))

rownames(grouped_data) = grouped_data$Bacteria
cor_data = t(grouped_data)
cor_data = as.data.frame(cor_data[-1,])
cor_data[] = lapply(cor_data, as.numeric)
```

```{r warning=FALSE}
# correlation with Anaplasma phagocytophilum

correlations_ap = data.frame(Comparison = character(), Correlation = numeric())

for (i in 1:ncol(cor_data)){
  x = cor(cor_data$`Anaplasma phagocytophilum`, cor_data[[i]])
  y = data.frame(Comparison = sprintf("Anaplasma phagocytophilum vs. %s", colnames(cor_data[i])), Correlation = x)
  correlations_ap = rbind(correlations_ap, y)
}

correlations_ap = correlations_ap %>%
  arrange(desc(Correlation)) %>%
  slice(-1) # the first row is the bacteria vs itself
```

```{r warning=FALSE}
# correlation with Borreliella burgdorferi

correlations_bb = data.frame(Comparison = character(), Correlation = numeric())

for (i in 1:ncol(cor_data)){
  x = cor(cor_data$`Borreliella burgdorferi`, cor_data[[i]])
  y = data.frame(Comparison = sprintf("Borreliella burgdorferi vs. %s", colnames(cor_data[i])), Correlation = x)
  correlations_bb = rbind(correlations_bb, y)
}

correlations_bb = correlations_bb %>%
  arrange(desc(Correlation)) %>%
  slice(-1) # the first row is the bacteria vs itself
```

```{r warning=FALSE}
# correlation with Borrelia miyamotoi

correlations_bm = data.frame(Comparison = character(), Correlation = numeric())

for (i in 1:ncol(cor_data)){
  x = cor(cor_data$`Borrelia miyamotoi`, cor_data[[i]])
  y = data.frame(Comparison = sprintf("Borrelia miyamotoi vs. %s", colnames(cor_data[i])), Correlation = x)
  correlations_bm = rbind(correlations_bm, y)
}

correlations_bm = correlations_bm %>%
  arrange(desc(Correlation)) %>%
  slice(-1) # the first row is the bacteria vs itself
```


```{r}
# make table for poster
newdata = data.frame()
newdata = data.frame(Comparison = correlations_ap$Comparison[1:5], Correlation = correlations_ap$Correlation[1:5]) %>%
  rbind(newdata, data.frame(Comparison = correlations_bb$Comparison[1:5], Correlation = correlations_bb$Correlation[1:5])) %>%
  rbind(newdata, data.frame(Comparison = correlations_bm$Comparison[1:5], Correlation = correlations_bm$Correlation[1:5]))

knitr::kable(newdata)
```

```{r}
# extract bacteria only in tick 45F

bac_45F = list()

for (i in 1:nrow(data)){
  if (sum(data[i,2:4]) == 0 &
      data[i,5] != 0  &
      !(data$Bacteria[i] %in% c("Anaplasma phagocytophilum", # remove bacteria with multiple instances (misleading positives)
                                  "Borreliella burgdorferi",
                                  "Rickettsia buchneri",
                                  "Borrelia miyamotoi",
                                "Rickettsia endosymbiont of Ixodes scapularis"))){ 
    bac_45F[[length(bac_45F)+1]] = data$Bacteria[i]
  }
}

bac_45F
```




